# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 10:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator('\\d{1,2}[ABM]?')])),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.PositiveSmallIntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (11, '11'), (24, '24'), (27, '27'), (28, '28'), (32, '32'), (44, '44'), (52, '52'), (53, '53'), (75, '75'), (76, '76'), (84, '84'), (93, '93'), (94, '94')], primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(1)])),
                ('population', models.PositiveIntegerField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.District')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='town',
            unique_together=set([('code', 'district')]),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together=set([('code', 'department')]),
        ),
    ]
