# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 10:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.RegexValidator('\\d{1,3}[ABM]?')]),
        ),
    ]
