##############################################################################
# Simple Dockerfile to use the stock nginx image and copy the config file
# into place
#
# VERSION          0.0.1
##############################################################################
FROM nginx

LABEL maintainer="leamingrad"

ADD nginx.conf /etc/nginx/nginx.conf
